server:
  port: 8082
  servlet:
    context-path: /inventory
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productinventory
      url: mongodb://localhost:27017/productinventory


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
