package com.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.io.Serializable;

@Data
@DynamoDBTable(tableName = "Product")
public class ProductDynamoDB implements Serializable {
    @DynamoDBAttribute
    private String name;
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private Integer id;
    @DynamoDBAttribute
    private Integer price;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private Integer count;
}
