package com.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.io.Serializable;
import java.math.BigInteger;

@Data
@DynamoDBTable(tableName = "Product")
public class Product implements Serializable {
    @DynamoDBAttribute
    private String name;
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private int id;
    @DynamoDBAttribute
    private BigInteger price;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private Integer count;
}
